### ISSUE TITLE
Marquee Flickers when the last element reaches left, right or top, In Firefox Browser.

### ISSUE THREAD

**Issue by antony-jr** [devnomic/marquee#3]
Amazing work you have done here, it seems like TailwindCSS based marquee have this problem, it flickers in **Firefox** (Linux), it **works in Chromium** though, but not just Firefox.

Any thoughts why this might be the case?

**Comment by devnomic** [comment]
Unfortunately, I'm not sure why. The animation uses native CSS only. It works well on Firefox for Mac, though. 

I suspect it's browser bug in linux, maybe try to replace css variable in the tailwind config with fixed value (don't use css var).  Or maybe change the translateX in tailwind config into translate3d and try to see.

**Comment by antony-jr** [comment]
Yeah, I suppose its specific Linux, or maybe my plugins are doing something. Thanks for the prompt response.
